language: node_js
node_js:
  - "8"
before_install:
  - npm install -g npm@3
  - npm --version
  - npm install -g grunt-cli
install:
  - npm install
cache:
  directories:
    - node_modules
env:
  global:
    - NPM_CONFIG_PROGRESS="false"
matrix:
  fast_finish: true
script:
  - grunt dist --verbose
  - grunt test --verbose
